### ISSUE TITLE
不知道你这 sql2o与 http://www.sql2o.org/这个有多少区别

### ISSUE THREAD

**Issue by jnuc093** [bladejava/docs#5]
不知道你这 sql2o与 http://www.sql2o.org/这个有多少区别

**Comment by biezhi** [comment]
sql2o提供了简单方便的jdbc操作方法，blade-jdbc对其进行了一层封装，内置了缓存和连接池的功能。

具体可以查看这里：https://github.com/bladejava/blade-jdbc

目前线上一个项目在用这个：http://java-china.org
